### ISSUE TITLE
compile with Lazarus 2.0.6 with FPC 3.0.4

### ISSUE THREAD

**Issue by farox1** [jnewbigin/rawwrite#6]
Hi
i have try to compile the rawwritewin program under Lazarus/FPC and found some errors.
I managed to fix this errors and the program is built fine and working fine also, tested on a WinXP machine with Floppy.
The program run also without error on my Win7 machine but don't have a floppy drive onto this...so no more test where done.

If you are interested i will send you the changed source.

Thanks a lot for your program.

**Comment by jnewbigin** [comment]
Hi,
Why don't you open a pull-request and I'll have a look

**Comment by farox1** [comment]
I'm not so good at github..sorry, i have an account but don't have loaded nothing.
I could attach here a zip file with the files changed.
[rawwrite-fpc.zip](https://github.com/jnewbigin/rawwrite/files/5251724/rawwrite-fpc.zip)

**Comment by farox1** [comment]
Hi
I have done a pull-request with my changes. Hope i have done all things ok.
please check and if ok i'll close this Issue.
Thank you
